---
- name: corona data app deployment
  hosts: coronadata
  become: yes

  tasks:
    - name: Make sure docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start  docker service
      service:
        name: docker
        state: started

    - name: Start coronadata container  
      shell: "docker run bamb4boy/coronadata:latest"







